// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(AnkiParserFFI)
import AnkiParserFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_anki_parser_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_anki_parser_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Media store for accessing media files
 */
public protocol AnkiMediaStoreProtocol : AnyObject {
    
    /**
     * Get the number of media files
     */
    func count()  -> UInt32
    
    /**
     * Get data for a specific media file
     */
    func dataFor(filename: String)  -> Data?
    
    /**
     * Get all media filenames
     */
    func filenames()  -> [String]
    
}

/**
 * Media store for accessing media files
 */
open class AnkiMediaStore:
    AnkiMediaStoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_anki_parser_fn_clone_ankimediastore(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_anki_parser_fn_free_ankimediastore(pointer, $0) }
    }

    

    
    /**
     * Get the number of media files
     */
open func count() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_anki_parser_fn_method_ankimediastore_count(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get data for a specific media file
     */
open func dataFor(filename: String) -> Data? {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_anki_parser_fn_method_ankimediastore_data_for(self.uniffiClonePointer(),
        FfiConverterString.lower(filename),$0
    )
})
}
    
    /**
     * Get all media filenames
     */
open func filenames() -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_anki_parser_fn_method_ankimediastore_filenames(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnkiMediaStore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = AnkiMediaStore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> AnkiMediaStore {
        return AnkiMediaStore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: AnkiMediaStore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnkiMediaStore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: AnkiMediaStore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiMediaStore_lift(_ pointer: UnsafeMutableRawPointer) throws -> AnkiMediaStore {
    return try FfiConverterTypeAnkiMediaStore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiMediaStore_lower(_ value: AnkiMediaStore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAnkiMediaStore.lower(value)
}


/**
 * Represents a single card with its fields
 */
public struct AnkiCard {
    public let id: Int64
    public let noteId: Int64
    public let deckId: Int64
    /**
     * Card fields (front, back, extra, etc.)
     */
    public let fields: [String]
    /**
     * Media file references found in the card
     */
    public let mediaReferences: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, noteId: Int64, deckId: Int64, 
        /**
         * Card fields (front, back, extra, etc.)
         */fields: [String], 
        /**
         * Media file references found in the card
         */mediaReferences: [String]) {
        self.id = id
        self.noteId = noteId
        self.deckId = deckId
        self.fields = fields
        self.mediaReferences = mediaReferences
    }
}



extension AnkiCard: Equatable, Hashable {
    public static func ==(lhs: AnkiCard, rhs: AnkiCard) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.noteId != rhs.noteId {
            return false
        }
        if lhs.deckId != rhs.deckId {
            return false
        }
        if lhs.fields != rhs.fields {
            return false
        }
        if lhs.mediaReferences != rhs.mediaReferences {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(noteId)
        hasher.combine(deckId)
        hasher.combine(fields)
        hasher.combine(mediaReferences)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnkiCard: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnkiCard {
        return
            try AnkiCard(
                id: FfiConverterInt64.read(from: &buf), 
                noteId: FfiConverterInt64.read(from: &buf), 
                deckId: FfiConverterInt64.read(from: &buf), 
                fields: FfiConverterSequenceString.read(from: &buf), 
                mediaReferences: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: AnkiCard, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterInt64.write(value.noteId, into: &buf)
        FfiConverterInt64.write(value.deckId, into: &buf)
        FfiConverterSequenceString.write(value.fields, into: &buf)
        FfiConverterSequenceString.write(value.mediaReferences, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiCard_lift(_ buf: RustBuffer) throws -> AnkiCard {
    return try FfiConverterTypeAnkiCard.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiCard_lower(_ value: AnkiCard) -> RustBuffer {
    return FfiConverterTypeAnkiCard.lower(value)
}


/**
 * Main collection container returned after parsing
 */
public struct AnkiCollection {
    /**
     * All decks in the collection
     */
    public let decks: [AnkiDeck]
    /**
     * Root-level decks only (no parent)
     */
    public let rootDecks: [AnkiDeck]
    /**
     * Cards grouped by deck ID (as string key for UniFFI compatibility)
     */
    public let cardsByDeck: [String: [AnkiCard]]
    /**
     * Media store for accessing media files
     */
    public let media: AnkiMediaStore

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * All decks in the collection
         */decks: [AnkiDeck], 
        /**
         * Root-level decks only (no parent)
         */rootDecks: [AnkiDeck], 
        /**
         * Cards grouped by deck ID (as string key for UniFFI compatibility)
         */cardsByDeck: [String: [AnkiCard]], 
        /**
         * Media store for accessing media files
         */media: AnkiMediaStore) {
        self.decks = decks
        self.rootDecks = rootDecks
        self.cardsByDeck = cardsByDeck
        self.media = media
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnkiCollection: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnkiCollection {
        return
            try AnkiCollection(
                decks: FfiConverterSequenceTypeAnkiDeck.read(from: &buf), 
                rootDecks: FfiConverterSequenceTypeAnkiDeck.read(from: &buf), 
                cardsByDeck: FfiConverterDictionaryStringSequenceTypeAnkiCard.read(from: &buf), 
                media: FfiConverterTypeAnkiMediaStore.read(from: &buf)
        )
    }

    public static func write(_ value: AnkiCollection, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeAnkiDeck.write(value.decks, into: &buf)
        FfiConverterSequenceTypeAnkiDeck.write(value.rootDecks, into: &buf)
        FfiConverterDictionaryStringSequenceTypeAnkiCard.write(value.cardsByDeck, into: &buf)
        FfiConverterTypeAnkiMediaStore.write(value.media, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiCollection_lift(_ buf: RustBuffer) throws -> AnkiCollection {
    return try FfiConverterTypeAnkiCollection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiCollection_lower(_ value: AnkiCollection) -> RustBuffer {
    return FfiConverterTypeAnkiCollection.lower(value)
}


/**
 * Represents a deck with hierarchy support
 */
public struct AnkiDeck {
    public let id: Int64
    /**
     * Full name with "::" separators (e.g., "Parent::Child::Grandchild")
     */
    public let name: String
    /**
     * Just the leaf name (e.g., "Grandchild")
     */
    public let shortName: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, 
        /**
         * Full name with "::" separators (e.g., "Parent::Child::Grandchild")
         */name: String, 
        /**
         * Just the leaf name (e.g., "Grandchild")
         */shortName: String) {
        self.id = id
        self.name = name
        self.shortName = shortName
    }
}



extension AnkiDeck: Equatable, Hashable {
    public static func ==(lhs: AnkiDeck, rhs: AnkiDeck) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.shortName != rhs.shortName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(shortName)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnkiDeck: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnkiDeck {
        return
            try AnkiDeck(
                id: FfiConverterInt64.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                shortName: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AnkiDeck, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.shortName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiDeck_lift(_ buf: RustBuffer) throws -> AnkiDeck {
    return try FfiConverterTypeAnkiDeck.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiDeck_lower(_ value: AnkiDeck) -> RustBuffer {
    return FfiConverterTypeAnkiDeck.lower(value)
}


/**
 * Error types that can occur during Anki file parsing
 */
public enum AnkiError {

    
    
    case FileNotFound(String
    )
    case InvalidArchive
    case DatabaseError(String
    )
    case DecompressionError(String
    )
    case MediaError(String
    )
    case JsonError(String
    )
    case IoError(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnkiError: FfiConverterRustBuffer {
    typealias SwiftType = AnkiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnkiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .FileNotFound(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidArchive
        case 3: return .DatabaseError(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .DecompressionError(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .MediaError(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .JsonError(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .IoError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AnkiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .FileNotFound(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .InvalidArchive:
            writeInt(&buf, Int32(2))
        
        
        case let .DatabaseError(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .DecompressionError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .MediaError(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .JsonError(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .IoError(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension AnkiError: Equatable, Hashable {}

extension AnkiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Progress states during parsing
 */

public enum AnkiProgress {
    
    case extracting
    case readingDecks
    case readingCards
    case processingMedia
    case complete
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnkiProgress: FfiConverterRustBuffer {
    typealias SwiftType = AnkiProgress

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnkiProgress {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .extracting
        
        case 2: return .readingDecks
        
        case 3: return .readingCards
        
        case 4: return .processingMedia
        
        case 5: return .complete
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AnkiProgress, into buf: inout [UInt8]) {
        switch value {
        
        
        case .extracting:
            writeInt(&buf, Int32(1))
        
        
        case .readingDecks:
            writeInt(&buf, Int32(2))
        
        
        case .readingCards:
            writeInt(&buf, Int32(3))
        
        
        case .processingMedia:
            writeInt(&buf, Int32(4))
        
        
        case .complete:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiProgress_lift(_ buf: RustBuffer) throws -> AnkiProgress {
    return try FfiConverterTypeAnkiProgress.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnkiProgress_lower(_ value: AnkiProgress) -> RustBuffer {
    return FfiConverterTypeAnkiProgress.lower(value)
}



extension AnkiProgress: Equatable, Hashable {}






/**
 * Progress callback trait for Swift to implement
 */
public protocol AnkiProgressCallback : AnyObject {
    
    func onProgress(progress: AnkiProgress) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceAnkiProgressCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceAnkiProgressCallback = UniffiVTableCallbackInterfaceAnkiProgressCallback(
        onProgress: { (
            uniffiHandle: UInt64,
            progress: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAnkiProgressCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     progress: try FfiConverterTypeAnkiProgress.lift(progress)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceAnkiProgressCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface AnkiProgressCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitAnkiProgressCallback() {
    uniffi_anki_parser_fn_init_callback_vtable_ankiprogresscallback(&UniffiCallbackInterfaceAnkiProgressCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceAnkiProgressCallback {
    fileprivate static var handleMap = UniffiHandleMap<AnkiProgressCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceAnkiProgressCallback : FfiConverter {
    typealias SwiftType = AnkiProgressCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAnkiCard: FfiConverterRustBuffer {
    typealias SwiftType = [AnkiCard]

    public static func write(_ value: [AnkiCard], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAnkiCard.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AnkiCard] {
        let len: Int32 = try readInt(&buf)
        var seq = [AnkiCard]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAnkiCard.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAnkiDeck: FfiConverterRustBuffer {
    typealias SwiftType = [AnkiDeck]

    public static func write(_ value: [AnkiDeck], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAnkiDeck.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AnkiDeck] {
        let len: Int32 = try readInt(&buf)
        var seq = [AnkiDeck]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAnkiDeck.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringSequenceTypeAnkiCard: FfiConverterRustBuffer {
    public static func write(_ value: [String: [AnkiCard]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterSequenceTypeAnkiCard.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [AnkiCard]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [AnkiCard]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterSequenceTypeAnkiCard.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
/**
 * Clean HTML content to Markdown
 *
 * This function is exported for Swift to use if needed for additional processing.
 * Converts:
 * - [sound:file.mp3] → [🔊 file.mp3](media:file.mp3)
 * - <img src="file.jpg"> → ![file.jpg](media:file.jpg)
 * - HTML tags → stripped or converted to newlines
 * - HTML entities → decoded
 */
public func cleanHtmlToMarkdown(html: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_anki_parser_fn_func_clean_html_to_markdown(
        FfiConverterString.lower(html),$0
    )
})
}
/**
 * Parse an Anki .apkg or .colpkg file
 *
 * # Arguments
 * * `file_path` - Path to the .apkg or .colpkg file
 * * `progress_callback` - Callback to report parsing progress
 *
 * # Returns
 * * `AnkiCollection` containing all decks, cards, and media
 *
 * # Errors
 * * `AnkiError::FileNotFound` - File does not exist
 * * `AnkiError::InvalidArchive` - Not a valid Anki archive
 * * `AnkiError::DatabaseError` - Error reading SQLite database
 * * `AnkiError::DecompressionError` - Error decompressing zstd data
 */
public func parseAnkiFile(filePath: String, progressCallback: AnkiProgressCallback)throws  -> AnkiCollection {
    return try  FfiConverterTypeAnkiCollection.lift(try rustCallWithError(FfiConverterTypeAnkiError.lift) {
    uniffi_anki_parser_fn_func_parse_anki_file(
        FfiConverterString.lower(filePath),
        FfiConverterCallbackInterfaceAnkiProgressCallback.lower(progressCallback),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_anki_parser_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_anki_parser_checksum_func_clean_html_to_markdown() != 63570) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_anki_parser_checksum_func_parse_anki_file() != 47480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_anki_parser_checksum_method_ankimediastore_count() != 35784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_anki_parser_checksum_method_ankimediastore_data_for() != 58668) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_anki_parser_checksum_method_ankimediastore_filenames() != 15136) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_anki_parser_checksum_method_ankiprogresscallback_on_progress() != 11340) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitAnkiProgressCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all